### ISSUE TITLE
Startup script after /usr/sbin/init 

### ISSUE THREAD

**Issue by JsonFn** [CentOS/sig-cloud-instance-images#118]
Following threads are the closest to my problem, but they fail to provide the fix.   

https://stackoverflow.com/questions/48720049/dockerfile-running-usr-sbin-init

https://github.com/CentOS/sig-cloud-instance-images/issues/28

My problem is with centos7 docker image I need to execute some procedures, installation (not something systemctl <service> start) once after init is executed as PID 1. However solutions provide on the internet (that describe either placing init in script with background execution i.e. `/usr/sbin/init&` or `exec /usr/sbin/init`), all of them don't work. 

    # Dockerfile
    ENTRYPOINT (or CMD) ["/path/to/startup-script"]

    # startup-script
    #!/bin/sh
    exec /usr/sbin/init # <- with this commands after this line won't get executed
    # /usr/sbin/init & # <- init is not executed as PID 1, it complains and then fails causing D-Bus error. 

How can I fix this if I need to auto execute some commands after /usr/sbin/init get executed?

Thanks

**Comment by mcauto** [comment]
I recommend this docker-compose.yml
```yaml
version: '2'
services:
  centos:
    build:
      context: .
      dockerfile: your_dockerfile
    image: centos
    hostname: centos
    container_name: centos
    tty: true # you should add
```
and 

```bash
$ docker-compose up -d
```

tty option is uesful.

this repo's images haven't /sbin/init.
